name: NodeJS with Webpack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: https://dev.getautoclicker.com/
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
         always-auth: true
         node-version: 16
         registry-url: https://npm.pkg.github.com
         scope: "@dhruv-techapps"
         cache: "npm"
    - name: Build
      run: |
        npm install
        npx webpack
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: downloads
      env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
