name: Build Extension

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
  
env:
    UNINSTALL_URL: ${{vars.UNINSTALL_URL}}
    TRACKING_ID: ${{vars.TRACKING_ID}}
    OPTIONS_PAGE_URL: ${{vars.OPTIONS_PAGE_URL}}
    FUNCTION_URL: ${{vars.FUNCTION_URL}}
    VARIANT: ${{vars.VARIANT}}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: https://dev.getautoclicker.com/
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Env
      uses: actions/setup-node@v3
      with:
         always-auth: true
         node-version: 16
         registry-url: https://npm.pkg.github.com
         scope: "@dhruv-techapps"
         cache: "npm"
    - name: Build Extension
      run: |
        npm install
        npx webpack --env name="${{vars.NAME}}" devtool="${{vars.DEV_TOOL}}" variant="${{vars.VARIANT}}"
    - name: Set DEV Tag
      uses: rickstaa/action-create-tag@v1
      with:
        force_push_tag: true
        tag: "DEV"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        generate_release_notes: true
        files: build/*
        fail_on_unmatched_files: true
